// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_corr
DataFrame rcpp_corr(DataFrame df1, DataFrame df2, StringVector Method);
RcppExport SEXP _TEKRABber_rcpp_corr(SEXP df1SEXP, SEXP df2SEXP, SEXP MethodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df1(df1SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df2(df2SEXP);
    Rcpp::traits::input_parameter< StringVector >::type Method(MethodSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_corr(df1, df2, Method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TEKRABber_rcpp_corr", (DL_FUNC) &_TEKRABber_rcpp_corr, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_TEKRABber(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
