# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate the correlation between genes and transposable elements
#' 
#' @param df1 First dataframe
#' @param df2 Second dataframe
#' @param Method correlation method
#' @return a dataframe containing correlation results
rcpp_corr <- function(df1, df2, Method) {
    .Call('_TEKRABber_rcpp_corr', PACKAGE = 'TEKRABber', df1, df2, Method)
}

